### ISSUE TITLE
"$app/env" imports not working

### ISSUE THREAD

**Issue by saikatdas0790** [rossyman/svelte-add-jest#12]
# Steps to reproduce
- init sveltekit with skeleton repo and choose yes for all
- run svelte-add-jest and choose yes for all
- test fails
- add h1 with "Hello world!"
- test passes
- import {browser} from "$app/env";
- jest starts freaking out

Here's a repo with a minimal reproduction
https://github.com/s-go-bazzinga/svelte-add-jest-tryout

**Comment by saikatdas0790** [comment]
I see that the `jest.config.json` has mappings for `env` but they don't seem to be working

![image](https://user-images.githubusercontent.com/7412443/126767421-5a1aab28-3c34-40b9-a7e7-e8f126282711.png)

**Comment by rossyman** [comment]
This issue was fixed in `v1.1.4`

**Comment by s-go-bazzinga** [comment]
@rossyman So, after updating the `$app` "moduleNameMapper", I believe the module is detected but further vite specific stuff makes jest croak. Here's what I get after updating.

![image](https://user-images.githubusercontent.com/79742177/126858188-62ae4af5-7f59-4f16-b431-f3f1b44cb119.png)

**Comment by saikatdas0790** [comment]
@rossyman So, after updating the `$app` "moduleNameMapper", I believe the module is detected but further vite specific stuff makes jest croak. Here's what I get after updating.

![image](https://user-images.githubusercontent.com/7412443/126858219-55d6f908-2db4-4556-9c4c-641fac6a61f4.png)

Link to minimal reproduction:
https://github.com/s-go-bazzinga/svelte-add-jest-tryout

@rossyman 
Let me know if I should open a separate issue for this?

**Comment by rossyman** [comment]
We're looking into this in #14 @saikatdas0790
