### ISSUE TITLE
Babel should be used only with TypeScript?

### ISSUE THREAD

**Issue by benmccann** [rossyman/svelte-add-jest#17]
I'm wondering if Babel and associated libraries should have `reliesOn: 'ts'`. It's not clear to me what we would be using that would otherwise require the code to be transformed

**Comment by rossyman** [comment]
I believe `babel-jest` and the associated libraries were added to _ensure_ ES6 module support... That being said, I'm not entirely sure whether or not Svelte/SvelteKit utilises this or not, or if this is even something we need to care about in this adder -- Can see the point I followed here under section `5.`: https://testing-library.com/docs/svelte-testing-library/setup#jest

**Comment by rossyman** [comment]
> I believe `babel-jest` and the associated libraries were added to _ensure_ ES6 module support... That being said, I'm not entirely sure whether or not Svelte/SvelteKit utilises this or not, or if this is even something we need to care about in this adder -- Can see the point I followed here under section `5.`: https://testing-library.com/docs/svelte-testing-library/setup#jest

Since this part is entirely optional, I could just add in another configuration option to the adder to leave this decision up to the developer whether to add this -- That being said, I should probably do this for testing-library in general, as it may be that users **just** want Jest.

**Comment by benmccann** [comment]
AH, thanks for the clarification!
