### ISSUE TITLE
generate test file option generates nothing

### ISSUE THREAD

**Issue by benmccann** [rossyman/svelte-add-jest#22]
I answered the following:
```
[ question ]  Enable Jest DOM support? (Y/n) · false
[ question ]  Enable TypeScript support? (y/N) · false
[ question ]  Generate example test file? (Y/n) · true
```

No example test file was generated. It should either not ask the last question or generate a test file that doesn't depend on the DOM

**Comment by rossyman** [comment]
Investigating now, this was something that was already on my radar.

**Comment by rossyman** [comment]
Raised a PR for this issue and for v27 Jest support -- Let me know your thoughts on the solution.
