### ISSUE TITLE
Current tests don't match latest create-svelte template

### ISSUE THREAD

**Issue by sebastianrothe** [rossyman/svelte-add-jest#28]
It seems the string that is searched in `index-dom.spec.ts` doesn't match anymore. https://github.com/sveltejs/kit/blob/master/packages/create-svelte/templates/default/src/routes/index.svelte

**Comment by rmunn** [comment]
It matches if you've created a skeleton project: https://github.com/sveltejs/kit/blob/master/packages/create-svelte/templates/skeleton/src/routes/index.svelte

But it would be good for svelte-add-jest to be able to determine whether it's being added to a skeleton project or a demo app, and install the correct example test accordingly.

Or the test could be changed to `expect(renderedComponent.getByText(/SvelteKit/)).toBeInTheDocument();` which would match against both the demo app and the skeleton template.
