### ISSUE TITLE
"Unexpected token / in JSON"

### ISSUE THREAD

**Issue by ehrencrona** [rossyman/svelte-add-jest#29]
When using the command on an empty SvelteKit project  I always get "Could not read the JSON file". 

SvelteKit version 1.0.0-next.171_svelte@3.43.0

Steps to reproduce:

```
pnpm init svelte@next addjest

✔ Which Svelte app template? › SvelteKit demo app. // i've tried skeleton app too with the same result
✔ Use TypeScript? … Yes
✔ Add ESLint for code linting? … No
✔ Add Prettier for code formatting? … Yes

cd addjest/
pnpm i
npx apply rossyman/svelte-add-jest

[ info ]  Applying preset rossyman/svelte-add-jest.
[ question ]  Enable Jest DOM support? (Y/n) · false
[ question ]  Enable TypeScript support? (y/N) · true
[ question ]  Generate example test file? (Y/n) · true
[ question ]  Enable JSDOM environment by default? (Y/n) · false
[ info ]  Adding required dependencies
[ info ]  Initializing Jest config
[ info ]  Initializing Babel config
[ info ]  Modifying TypeScript config for project
[ error ]  Could not read the JSON file.
SyntaxError: Unexpected token / in JSON at position 128
    at JSON.parse (<anonymous>)
    at EditJsonHandler.getContent (.../node_modules/apply/dist/Handlers/EditJsonHandler.js:58:50)
    at EditJsonHandler.handle (.../node_modules/apply/dist/Handlers/EditJsonHandler.js:28:42)
    at PresetApplier.performActions (.../node_modules/apply/dist/Applier/PresetApplier.js:78:27)
```

**Comment by yogenpoonudurai** [comment]
> When using the command on an empty SvelteKit project I always get "Could not read the JSON file".
> 
> SvelteKit version 1.0.0-next.171_svelte@3.43.0
> 
> Steps to reproduce:
> 
> ```
> pnpm init svelte@next addjest
> 
> ✔ Which Svelte app template? › SvelteKit demo app. // i've tried skeleton app too with the same result
> ✔ Use TypeScript? … Yes
> ✔ Add ESLint for code linting? … No
> ✔ Add Prettier for code formatting? … Yes
> 
> cd addjest/
> pnpm i
> npx apply rossyman/svelte-add-jest
> 
> [ info ]  Applying preset rossyman/svelte-add-jest.
> [ question ]  Enable Jest DOM support? (Y/n) · false
> [ question ]  Enable TypeScript support? (y/N) · true
> [ question ]  Generate example test file? (Y/n) · true
> [ question ]  Enable JSDOM environment by default? (Y/n) · false
> [ info ]  Adding required dependencies
> [ info ]  Initializing Jest config
> [ info ]  Initializing Babel config
> [ info ]  Modifying TypeScript config for project
> [ error ]  Could not read the JSON file.
> SyntaxError: Unexpected token / in JSON at position 128
>     at JSON.parse (<anonymous>)
>     at EditJsonHandler.getContent (.../node_modules/apply/dist/Handlers/EditJsonHandler.js:58:50)
>     at EditJsonHandler.handle (.../node_modules/apply/dist/Handlers/EditJsonHandler.js:28:42)
>     at PresetApplier.performActions (.../node_modules/apply/dist/Applier/PresetApplier.js:78:27)
> ```

I faced the similar error. Removed the comments in the tsconfig.json file and ran the script again. And then it worked.

**Comment by rossyman** [comment]
Hi @ehrencrona and @firacloudtech -- We outlined this nuance within our README. Due to a lack of support from Preset to parse JSON-C files, this is something we cannot fix directly within our adder. I'm going to close this issue and mark it as wont-fix.

### README Screenshot

<img width="878" alt="Screenshot 2021-11-27 at 21 55 02" src="https://user-images.githubusercontent.com/10212476/143721725-9e438607-e769-455f-a3bd-5d6544277e50.png">
