### ISSUE TITLE
 Unexpected token / in JSON at position 128

### ISSUE THREAD

**Issue by damiensawyer** [rossyman/svelte-add-jest#32]
Hi, 

I hope you don't mind the image. 

I'm running in cygwin on Windows. Not sure if that's the issue. It's usually fine. 

![image](https://user-images.githubusercontent.com/891307/146925455-398622f0-3362-42e7-b15a-515541db35b6.png)

Cheers.

**Comment by rossyman** [comment]
Please see this: https://github.com/rossyman/svelte-add-jest/issues/29
