### ISSUE TITLE
Windows not supported

### ISSUE THREAD

**Issue by sebastianrothe** [rossyman/svelte-add-jest#33]
The test script requires the setting of `NODE_OPTIONS`, which is not supported under Windows unless `cross-env` is added as a prefix.

The following steps are required to get it working under Windows:
1. install cross-env as a devDependency
2. Add `cross-env` in front of `NODE_OPTIONS` at https://github.com/rossyman/svelte-add-jest/blob/main/preset.ts#L246

**Comment by rossyman** [comment]
I'll investigate this further; while adding `cross-env` as a dependency to enable this flag is an elegant solution, I don't want to drive other peoples testing configuration further than we already do -- In regards to this, I'm currently working on phasing out this version of `svelte-add-jest` to something less opinionated too.
