### ISSUE TITLE
Error while testing component using module $app/env 

### ISSUE THREAD

**Issue by ThibaudMZN** [rossyman/svelte-add-jest#34]
Hi,

I'm running into some issues when trying to test a component that uses `$app/env `, 
I'm getting the following error :
```
  ● Test suite failed to run

    Configuration error:

    Could not locate module $app/env mapped as:
    [
      "/home/tmzn/work/sveltekit-test/.svelte-kit/dev/runtime/app/env",
      "/home/tmzn/work/sveltekit-test/.svelte-kit/build/runtime/app/env"
    ].

    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/^\$app(.*)$/": "[
          "/home/tmzn/work/sveltekit-test/.svelte-kit/dev/runtime/app$1",
          "/home/tmzn/work/sveltekit-test/.svelte-kit/build/runtime/app$1"
        ]"
      },
      "resolver": undefined
    }
```

When looking into my `.sveltekit` folder, I cannot find any `/dev` or `/runtime`, and if i try to modify my module name mapping as follows :

```
  "moduleNameMapper": {
    "^\\$lib(.*)$": "<rootDir>/src/lib$1",
    "^\\$app(.*)$":
      "<rootDir>/.svelte-kit/runtime/app$1"
  },
```

I'm getting this error :

```
    TypeError: Cannot read property 'SSR' of undefined

      4 |  * @type {import('$app/env').browser}
      5 |  */
    > 6 | const browser = !import.meta.env.SSR;
        |                                  ^
      7 | /**
      8 |  * @type {import('$app/env').dev}
      9 |  */

      at .svelte-kit/runtime/app/env.js:6:34
```

I've created a skeleton project with `npm init svelte@next`, using all default values except using typescript, and added a `room.svelte` file as follows :

```
<script>
	import { browser } from '$app/env';

	if (browser) {
        console.log("Hello from browser");
	}
</script>

<section>
    <div>Hello</div>
</section>
```

And the test `room-dom.spec.ts` :

```
/**
 * @jest-environment jsdom
 */

 import { render, RenderResult } from '@testing-library/svelte';
 import Room from './room.svelte';
 
 
 describe('Room', () => {
 
   let renderedComponent: RenderResult;
 
   beforeEach(() => {
     renderedComponent = render(Room);
   });
 
   describe('once the component has been rendered', () => {
 
     test('should show the proper heading', () => {
       expect(renderedComponent.getByText(/Hello/)).toBeInTheDocument();
     });
 
   });
 
 });
```

**Comment by NLObedear** [comment]
I have the same issue, did you find a solution to it?

**Comment by rossyman** [comment]
I'll look into this further, thanks for logging the bug 🙂

**Comment by LeoUrzua** [comment]
Same issue using typescript

**Comment by rossyman** [comment]
After looking into this further, this issue is related to: https://github.com/rossyman/svelte-add-jest/issues/14. Please see [this comment](https://github.com/rossyman/svelte-add-jest/issues/14#issuecomment-916464335) for further information on how to solve your issue.

I'll investigate this issue a bit more and see what we can do on our side since that issue has been open for quite a while. I'll close this issue in the meantime and any followup will be logged under https://github.com/rossyman/svelte-add-jest/issues/14
