### ISSUE TITLE
Solution to vite pulling in `routes/**/*.spec.ts`

### ISSUE THREAD

**Issue by jtlapp** [rossyman/svelte-add-jest#35]
I needed to add this package to an existing repo, violating the precondition requirement that "You must start with a fresh copy of the official SvelteKit template." I don't know if this caused my problem, but the demo `routes/index.spec.ts` bombed vite:

![Screen Shot 2022-03-22 at 14 24 14](https://user-images.githubusercontent.com/138133/159559652-f1e0e9df-7d64-4a55-b263-870da284f4ad.png)

I solved the problem by modifying `svelte.config.js` based on [this SO answer](https://stackoverflow.com/a/69457826/650894). This is my new config file:

```js
import adapter from '@sveltejs/adapter-auto';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
    // Consult https://github.com/sveltejs/svelte-preprocess
    // for more information about preprocessors
    preprocess: preprocess(),

    kit: {
        adapter: adapter(),
        routes: filepath => {
            return ![
                // exclude *test.js files
                /\.spec\.ts$/,

                // original default config
                /(?:(?:^_|\/_)|(?:^\.|\/\.)(?!well-known))/,
            ].some(regex => regex.test(filepath))
        },
    }
};

export default config;
```

I don't know if my violating the precondition requirement caused the problem, but I had an existing repo, and I needed the package.

**Comment by rossyman** [comment]
I'm happy enough with this as a solution to Vite picking up `.spec` files as a route. I'll raise a PR to include this extra reg-ex exclusion

**Comment by rossyman** [comment]
After further inspection, I've found that the library we're using to apply the preset, doesn't allow the modification of JS files. Therefore, I'm going to update the documentation around this issue, and raise a PR to close this one off. Cheers for the help 😄
