### ISSUE TITLE
jest doesn't exist as an adder

### ISSUE THREAD

**Issue by bertrandlalo** [rossyman/svelte-add-jest#5]
Dear authors, 

First of all, thank you for the repo initiative! 

I'm trying to configure jest test on a SvelteKit project. 

Here is what I did : 
- Node v14.15.0
- I ran `npm init svelte@next` and chose typescript
- I removed the commented lined in `tsconfig` file
- I ran `npx svelte-add jest`  

Here is the following output: 

```
npx: installed 61 in 3.123s
➕ Svelte Add (Version 2021.06.30.01)
The project directory you're giving to this command cannot be determined to be guaranteed fresh — maybe it is, maybe it isn't. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.

jest
  ❌ doesn't exist as an adder. Have you spelled it correctly?
```

Do you have any idea of what I might have done wrong? 

++

**Comment by rossyman** [comment]
We're going to resolve this soon. We were waiting on the `@svelte-add` org to update their architecture (therefore, we didn't merge our adder officially), however, we've decided to push on with what we have at the moment for the benefit of the community.

You can track the progress of the architecture change in the following issue:
- https://github.com/svelte-add/svelte-adders/issues/12

I'll also keep you updated with when you can use this adder @bertrandlalo

**Comment by rossyman** [comment]
Documentation's been updated -- Hope this clarifies things for you @bertrandlalo

**Comment by bertrandlalo** [comment]
Thank you very much 🙌

I'm trying `npx apply rossyman/svelte-add-jest`. but I have this error : 
`usage: apply [-a magic] [-d] [-0123456789] command arguments ...` 😔

And when I had the flag `no-ssh`, I get `no such file or directory: rossyman/svelte-add-jest` 

Any idea?


PS: If ever you had even an example of what files/config should be created after running those commands, it would help me a lot... I'm desperate to integrate some tests to my svelte-kit application....

**Comment by rossyman** [comment]
> Thank you very much 🙌
> 
> I'm trying `npx apply rossyman/svelte-add-jest`. but I have this error :
> `usage: apply [-a magic] [-d] [-0123456789] command arguments ...` 😔
> 
> And when I had the flag `no-ssh`, I get `no such file or directory: rossyman/svelte-add-jest`
> 
> Any idea?
> 
> PS: If ever you had even an example of what files/config should be created after running those commands, it would help me a lot... I'm desperate to integrate some tests to my svelte-kit application....

I'll try to replicate and investigate now, in the meantime, can you confirm that:
- a) You're running this command on a SvelteKit project
- b) You've CD'd into the SvelteKit project

**Comment by bertrandlalo** [comment]
Yes, I do confirm that I'm on a SvelteKit project. 
I even tried to do a fresh one from start using `npm init svelte@next`. 

I'm on MacOs, zsh, with Node v14.16.0. 

A friend tried on windows and got the following error: 
```
[ info ]  Applying preset rossyman/svelte-add-jest.
../../../Users/derfu/AppData/Local/Temp/tmp-16732-03YQ1klXEeNf/preset.ts:1:41: error: Could not resolve "comment-json" (mark it as external to exclude it from the bundle)
    1 │ import { assign, parse, stringify } from 'comment-json';
      ╵                                          ~~~~~~~~~~~~~~
  ```

**Comment by rossyman** [comment]
<img width="411" alt="Screenshot 2021-07-21 at 21 14 52" src="https://user-images.githubusercontent.com/10212476/126553968-daad5291-667d-4e23-a5f8-aa3a519676e0.png">

I've managed to replicate the issue and also seen the above error from your last message -- It's a known limitation of Preset (Which we use to orchestrate the changes) -- I'm working on a fix now.

**Comment by bertrandlalo** [comment]
Thank you so much. Let me know if there's anything I can do to help!

**Comment by rossyman** [comment]
We've rolled back the JSON-C changes for now, as Preset doesn't support modifying JSON files that have comments in them or have support for external dependencies. 

We've also raised an issue with the Preset team, specifically to do with making the error handling logic easier for us:
- https://github.com/preset/cli/issues/84

In the meantime, apart from the caveat of not being able to have comments in your `tsconfig.json` file when running our adder, you should be good to go! Let us know how it goes 😄 @bertrandlalo

**Comment by bertrandlalo** [comment]
Still have the error 😔
![issue-npx-add](https://user-images.githubusercontent.com/22340670/126561141-0c77e3d0-f413-4f65-b15b-3177b4b0929d.jpg)

**Comment by rossyman** [comment]
<img width="1076" alt="Screenshot 2021-07-21 at 22 30 50" src="https://user-images.githubusercontent.com/10212476/126562771-e0ced1ae-fca6-460a-acb6-c76b56a37c9d.png">

Interesting, I can't seem to replicate the error on my side. Give me some time to investigate again. Thanks for bearing with me.

**Comment by rossyman** [comment]
<img width="406" alt="Screenshot 2021-07-21 at 22 33 41" src="https://user-images.githubusercontent.com/10212476/126563064-ffdfdc9b-1a19-4fb2-a924-90e3e5315914.png">

One thing to note, is that ZSH / Mac seems to have a built in binary called `apply` -- I wonder if there's an issue in your path that seems to be causing your terminal to somehow use the built in `apply`, rather than the one sourced from the NPM registry.

**Comment by bertrandlalo** [comment]
Wow, great, nice catchI I used a bash terminal to see if zsh was the problem and it worked well 🙏👌🙌

(the test fails though on `expect(getByText('Hello world!')).toBeInTheDocument();` !

Thank you very much for your help. Tomorrow, I'll try to use all this on my actual project. 

💃❤️

**Comment by rossyman** [comment]
> Wow, great, nice catchI I used a bash terminal to see if zsh was the problem and it worked well 🙏👌🙌
> 
> (the test fails though on `expect(getByText('Hello world!')).toBeInTheDocument();` !
> 
> Thank you very much for your help. Tomorrow, I'll try to use all this on my actual project.
> 
> 💃❤️

Fab! The intention was for the test to fail -- Forces the developer to make it pass, if you don't want the example test files, you can pass in the `--no-examples` flag. I'll close this issue now, have a nice day 😄
